version: "3"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    hostname: 'sqlserver'
    volumes:
      - ms-sqlserver-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 
      MSSQL_PID: Developer
    ports:
      - '1433:1433'
volumes:
  ms-sqlserver-data:
    driver: local
